import { ConferenceMap } from "@/models";

export const mockTeamStats: ConferenceMap = {
  conference1: {
    team1: {
      name: "team1",
      logo: "logo1",
      mascot: "mascot1",
      possessions: "1",
      rpi: "1",
      "schedule-strength": "1",
      "primary-color": "primary1",
      "secondary-color": "secondary1",
      "stats-offensive": {
        "draw-foul-percentage": 1,
        "free-throw-percentage": 1,
        "offensive-rebound-percentage": 1,
        "three-point-percentage": 1,
        "two-point-attempt-percentage": 1,
        "two-point-percentage": 1,
      },
      "stats-defense": {
        "cause-turnover-percentage": 1,
        "commit-foul-percentage": 1,
        "defensive-rebound-percentage": 1,
        "opp-three-point-percentage": 1,
        "opp-two-point-percentage": 1,
      },
    },
  },
  conference2: {
    team2: {
      name: "team2",
      logo: "logo2",
      mascot: "mascot2",
      possessions: "2",
      rpi: "2",
      "schedule-strength": "2",
      "primary-color": "primary2",
      "secondary-color": "secondary2",
      "stats-offensive": {
        "draw-foul-percentage": 2,
        "free-throw-percentage": 2,
        "offensive-rebound-percentage": 2,
        "three-point-percentage": 2,
        "two-point-attempt-percentage": 2,
        "two-point-percentage": 2,
      },
      "stats-defense": {
        "cause-turnover-percentage": 2,
        "commit-foul-percentage": 2,
        "defensive-rebound-percentage": 2,
        "opp-three-point-percentage": 2,
        "opp-two-point-percentage": 2,
      },
    },
  },
  conference3: {
    team3: {
      name: "team3",
      logo: "logo3",
      mascot: "mascot3",
      possessions: "3",
      rpi: "3",
      "schedule-strength": "3",
      "primary-color": "primary3",
      "secondary-color": "secondary3",
      "stats-offensive": {
        "draw-foul-percentage": 3,
        "free-throw-percentage": 3,
        "offensive-rebound-percentage": 3,
        "three-point-percentage": 3,
        "two-point-attempt-percentage": 3,
        "two-point-percentage": 3,
      },
      "stats-defense": {
        "cause-turnover-percentage": 3,
        "commit-foul-percentage": 3,
        "defensive-rebound-percentage": 3,
        "opp-three-point-percentage": 3,
        "opp-two-point-percentage": 3,
      },
    },
  },
  conference4: {
    team4: {
      name: "team4",
      logo: "logo4",
      mascot: "mascot4",
      possessions: "4",
      rpi: "4",
      "schedule-strength": "4",
      "primary-color": "primary4",
      "secondary-color": "secondary4",
      "stats-offensive": {
        "draw-foul-percentage": 4,
        "free-throw-percentage": 4,
        "offensive-rebound-percentage": 4,
        "three-point-percentage": 4,
        "two-point-attempt-percentage": 4,
        "two-point-percentage": 4,
      },
      "stats-defense": {
        "cause-turnover-percentage": 4,
        "commit-foul-percentage": 4,
        "defensive-rebound-percentage": 4,
        "opp-three-point-percentage": 4,
        "opp-two-point-percentage": 4,
      },
    },
  },
};
