// Global CSS
import './globals.css'
// Fonts
import { Geologica } from 'next/font/google'

const geologica = Geologica({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={geologica.className}>{children}</body>
    </html>
  )
}
