import { z } from "zod";

export const UserTotalStatsSupabaseSchema = z.object({
  id: z.string().uuid().optional(),
  user_id: z.string().uuid(),
  year_id: z.string().uuid(),
  total_brackets: z.number(),
  total_picks: z.number(),
  total_correct_picks: z.number(),
  correct_pick_percentage: z.number(),
  high_score: z.number(),
  high_score_rank: z.number(),
  low_score: z.number(),
  average_score: z.number(),
  last_three_average_score: z.number(),
  last_ten_average_score: z.number(),
  average_score_rank: z.number(),
  total_first_round_upsets_picked: z.number(),
  total_first_round_upsets_correct: z.number(),
  first_round_upsets_correct_percentage: z.number(),
  champions_guessed_correctly: z.number(),
  champion_correct_percentage: z.number(),
  champions_guessed_correctly_rank: z.number(),
  top_picked_champion_id: z.string().uuid(),
  total_top_picked_champion_picks: z.number(),
  total_final_fours_picked: z.number(),
  final_fours_guessed_correctly: z.number(),
  final_four_correct_percentage: z.number(),
  total_elite_eights_picked: z.number(),
  elite_eights_guessed_correctly: z.number(),
  elite_eight_correct_percentage: z.number(),
  total_sweet_sixteens_picked: z.number(),
  sweet_sixteens_guessed_correctly: z.number(),
  sweet_sixteen_correct_percentage: z.number(),
  total_round_twos_picked: z.number(),
  rounds_two_guessed_correctly: z.number(),
  round_two_correct_percentage: z.number(),
  total_round_ones_picked: z.number(),
  rounds_one_guessed_correctly: z.number(),
  round_one_correct_percentage: z.number(),
  top_picked_conference_id: z.string().uuid(),
  total_top_picked_conference_picks: z.number(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export type UserTotalStatsSupabase = z.infer<
  typeof UserTotalStatsSupabaseSchema
>;
